// import './globals.css'
// import { Inter } from 'next/font/google' ;
// import Link from 'next/link';
// import 'bootstrap/dist/css/bootstrap.css' ;
// // import 'bootstrap/dist/js/bootstrap.bundle';
// import { SessionProvider, useSession } from "next-auth/react";


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


// export default function RootLayout({ children, session }) {
//   return (
    
   
//     <html lang="en">
//        <SessionProvider session={session} >
      
//     <body className={inter.className}>
    
//         {children}
       
   
//     </body>
//     </SessionProvider>     
    
     
//     </html>
    

    
  
//   )
// }
